language: generic

sudo: required

env:
  matrix:
    - DOCKERFILE=docker/ubuntu_20_04_lofar
    - DOCKERFILE=docker/ubuntu_20_04_nolofar

services:
  - docker

before_install:
- docker build -f $DOCKERFILE .
