#!/bin/sh

# mwflagger-part: A distributed part of mwflagger
#
# Copyright (C) 2009
# ASTRON (Netherlands Institute for Radio Astronomy)
# P.O.Box 2, 7990 AA Dwingeloo, The Netherlands
#
# This file is part of the LOFAR software suite.
# The LOFAR software suite is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# The LOFAR software suite is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with the LOFAR software suite. If not, see <http://www.gnu.org/licenses/>.
#
# @author Ger van Diepen <diepen AT astron nl>
#
# $Id$


# Find the path used to start the script.
pgmpath=`dirname $0`
pgmpath=`cd $pgmpath > /dev/null 2>&1  &&  pwd`

if test $# != 12; then
  echo "run as:   mwflagger-part dummy dummy dummy dummy rank"
  echo "                         ms-part filesys ms-part-vds envfile"
  echo "                         parset-file wd dry"
  exit 1
fi

shift
shift
shift
shift
seqnr=$1
msn=$2
envfile=$5
psn=$6
wd=$7
dry=$8

psnbase=`basename $psn`

# Initialize environment.
if test "$envfile" != ""; then
  . $envfile
fi

# Get the data set name and the directory name of it.
if test "$wd" = ""  -o  "$wd" = "..."; then
  wd=`dirname "$msn"`
fi

# Set to working directory.
cd $wd  ||  exit 1

echo "rficonsole $msn"
if test "$dry" != dry; then
  rficonsole $msn
fi
