#!/bin/sh

# Set srcdir if not defined (in case run by hand).
if test "$srcdir" = ""; then
  srcdir=`find ../../../../../.. -name PythonDPPP | grep -v build/ | grep -v /include/`/test
fi

if test ! -f $srcdir/../../DPPP/test/tNDPPP.in_MS.tgz; then
  return 3   # untested
fi

# Get the test MS and rename it to be deleted automatically.
tar zxf $srcdir/../../DPPP/test/tNDPPP.in_MS.tgz
mv tNDPPP_tmp.MS tPythonStep_tmp.MS

# Define the path for finding the library.
LD_LIBRARY_PATH=../src:$LD_LIBRARY_PATH
DYLD_LIBRARY_PATH=../src:$DYLD_LIBRARY_PATH
export LD_LIBRARY_PATH
export DYLD_LIBRARY_PATH

# Run NDPPP with the test python step.
NDPPP msin=tPythonStep_tmp.MS msout=tPythonStep_tmp.msout msout.overwrite=T steps='[pystep,pystep2]' pystep.type=PythonDPPP pystep.python.module=tPythonStep pystep.python.class=tPythonStep pystep.somekey=somevalue pystep2.type=pythondppp pystep2.python.class=tPythonStep pystep2.incr=3.5

