#!/bin/sh

# tmwflagger.run: Script to test mwflagger
#
# Copyright (C) 2009
# ASTRON (Netherlands Institute for Radio Astronomy)
# P.O.Box 2, 7990 AA Dwingeloo, The Netherlands
#
# This file is part of the LOFAR software suite.
# The LOFAR software suite is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# The LOFAR software suite is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with the LOFAR software suite. If not, see <http://www.gnu.org/licenses/>.
#
# $Id$


# Add . to PATH.
PATH=.:$PATH
export PATH

# Set srcdir if undefined (if run outside 'make check')
if test "$srcdir" = ""; then
  srcdir=../../../src
fi

# Do a test using the askap flagger.
# Enclose output in angle brackets to exclude it from the assay diff.
echo ">>>"
$srcdir/../src/mwflagger tmwflagger.parset tmwflagger.in_cd `pwd` tmwflagger_tmp.log dry tmwflagger_tmp.hfn
echo "<<<"

# Append the three log files to the output.
# Wait for the subprocesses to finish.
# Remove disturbing log4cxx lines
sleep 5
grep -v 'log4cxx:' tmwflagger_tmp.log-0
grep -v 'log4cxx:' tmwflagger_tmp.log-1
grep -v 'log4cxx:' tmwflagger_tmp.log-2
