FROM ubuntu

RUN export DEBIAN_FRONTEND=noninteractive && apt-get update && \
    apt-get install -y \
    libboost-python-dev libcfitsio-dev python3-dev python3-numpy cmake \
    build-essential libhdf5-serial-dev libarmadillo-dev \
    libboost-filesystem-dev libboost-system-dev libboost-date-time-dev \
    libboost-signals-dev libboost-program-options-dev libboost-test-dev \
    libxml2-dev libpng-dev pkg-config \
    libgtkmm-3.0-dev git libfftw3-dev \
    gfortran flex bison wcslib-dev \
    libboost-numpy-dev liblua5.3-dev

# Get casacore
RUN mkdir /casacore && cd /casacore && git clone -b v3.2.0 https://github.com/casacore/casacore.git src
RUN mkdir /casacore/build && cd /casacore/build && cmake -DBUILD_PYTHON3="ON" -DBUILD_PYTHON="OFF" -DUSE_HDF5="ON" -DCXX11="ON" -DCMAKE_INSTALL_PREFIX=/usr ../src && make install -j24

# Get aoflagger
RUN mkdir /aoflagger && cd /aoflagger && git clone git://git.code.sf.net/p/aoflagger/code src
RUN mkdir /aoflagger/build && cd /aoflagger/build && cmake -DCMAKE_INSTALL_PREFIX=/usr ../src && make install -j24

ADD . /src
WORKDIR /src
