FROM kernsuite/base:4

RUN export DEBIAN_FRONTEND=noninteractive && apt-get update && \
    apt-get install -y casacore-data casacore-dev \
    libboost-python-dev libcfitsio-dev python-dev python-numpy cmake \
    build-essential libhdf5-serial-dev libarmadillo-dev lofar-dev \
    libboost-filesystem-dev libboost-system-dev libboost-date-time-dev \
    libboost-signals-dev libboost-program-options-dev libboost-test-dev \
    libxml2-dev libpng-dev pkg-config aoflagger-dev \
    libgtkmm-3.0-dev git wget libfftw3-dev

ADD . /src
WORKDIR /src

# Build latest IDG master from source
RUN mkdir /idg && cd /idg && git clone https://gitlab.com/astron-idg/idg.git src
RUN mkdir /idg/build && cd /idg/build && cmake -DCMAKE_INSTALL_PREFIX=/usr/local ../src && make install -j2

RUN mkdir /build && cd /build && cmake -DCMAKE_PREFIX_PATH=/usr/local ../src
RUN ln -s /usr/include/casacore/measures /usr/include && ln -s /usr/include/casacore/ms /usr/include
RUN cd /build && make -j2
RUN cd /build && make install -j2
RUN DPPP
RUN cd /build && CTEST_OUTPUT_ON_FAILURE=1 make test -j2
