#!/bin/bash

# Get the taql executable and srcdir (script created by cmake's CONFIGURE_FILE).
source findenv.run_script
echo "srcdirx=$rt_srcdir"

# Set srcdir if not defined (in case run by hand).
if test "$srcdir" = ""; then
  srcdir="$rt_srcdir"
fi

if test ! -f ${srcdir}/tNDPPP-generic.in_MS.tgz; then
  exit 3   # untested
fi

set -e # Stop on any error

rm -rf tMultiApplyCal_tmp
mkdir -p tMultiApplyCal_tmp
# Unpack the MS and other files and do the DPPP run.
cd tMultiApplyCal_tmp
tar zxf ${srcdir}/tNDPPP-generic.in_MS.tgz

# Create expected taql output.
echo "    select result of 0 rows" > taql.ref

echo; echo "Creating parmdb with defvalues 3"
parmdbm <<EOL
open table="tApplyCal.parmdb"
adddef Gain:0:0:Real values=3.
adddef Gain:1:1:Real values=3.
adddef CommonScalarPhase values=0
EOL

cmd='NDPPP msin=tNDPPP-generic.MS checkparset=1 msout=. msout.datacolumn=DATA3 steps=[applycal] applycal.steps="[gain,csp]" applycal.gain.parmdb=tApplyCal.parmdb applycal.gain.correction=gain applycal.csp.parmdb=tApplyCal.parmdb applycal.csp.correction=commonscalarphase showcounts=false'
echo $cmd
eval $cmd
$taqlexe 'select from tNDPPP-generic.MS where not(all(DATA~=9*DATA3))' > taql.out
diff taql.out taql.ref  ||  exit 1

cmd='NDPPP msin=tNDPPP-generic.MS checkparset=1 msout=. msout.datacolumn=DATA3 steps=[applycal] applycal.steps="[gain,csp]" applycal.parmdb=tApplyCal.parmdb applycal.gain.correction=gain applycal.csp.correction=commonscalarphase showcounts=false'
echo $cmd
eval $cmd
$taqlexe 'select from tNDPPP-generic.MS where not(all(DATA~=9*DATA3))' > taql.out
diff taql.out taql.ref  ||  exit 1

